// @generated by script_bindings build.rs — DO NOT EDIT

pub static CONSOLE_METHODS: phf::Map<&'static str, MethodInfo> = ::phf::Map {
    key: 7485420634051515786,
    disps: &[
        (3, 0),
        (2, 7),
        (5, 2),
        (2, 6),
    ],
    entries: &[
        ("groupEnd", MethodInfo { name: "groupEnd", arity: 0, is_variadic: false, return_type: "undefined" }),
        ("clear", MethodInfo { name: "clear", arity: 0, is_variadic: false, return_type: "undefined" }),
        ("assert", MethodInfo { name: "assert", arity: 2, is_variadic: true, return_type: "undefined" }),
        ("error", MethodInfo { name: "error", arity: 1, is_variadic: true, return_type: "undefined" }),
        ("timeLog", MethodInfo { name: "timeLog", arity: 2, is_variadic: true, return_type: "undefined" }),
        ("group", MethodInfo { name: "group", arity: 1, is_variadic: true, return_type: "undefined" }),
        ("groupCollapsed", MethodInfo { name: "groupCollapsed", arity: 1, is_variadic: true, return_type: "undefined" }),
        ("dir", MethodInfo { name: "dir", arity: 2, is_variadic: false, return_type: "undefined" }),
        ("debug", MethodInfo { name: "debug", arity: 1, is_variadic: true, return_type: "undefined" }),
        ("log", MethodInfo { name: "log", arity: 1, is_variadic: true, return_type: "undefined" }),
        ("time", MethodInfo { name: "time", arity: 1, is_variadic: false, return_type: "undefined" }),
        ("info", MethodInfo { name: "info", arity: 1, is_variadic: true, return_type: "undefined" }),
        ("warn", MethodInfo { name: "warn", arity: 1, is_variadic: true, return_type: "undefined" }),
        ("timeEnd", MethodInfo { name: "timeEnd", arity: 1, is_variadic: false, return_type: "undefined" }),
        ("countReset", MethodInfo { name: "countReset", arity: 1, is_variadic: false, return_type: "undefined" }),
        ("count", MethodInfo { name: "count", arity: 1, is_variadic: false, return_type: "undefined" }),
        ("trace", MethodInfo { name: "trace", arity: 1, is_variadic: true, return_type: "undefined" }),
        ("table", MethodInfo { name: "table", arity: 2, is_variadic: false, return_type: "undefined" }),
    ],
};
pub static NAMESPACES: phf::Map<&'static str, NamespaceInfo> = ::phf::Map {
    key: 12913932095322966823,
    disps: &[
        (0, 0),
    ],
    entries: &[
        ("console", NamespaceInfo { name: "console", methods: &CONSOLE_METHODS }),
    ],
};
pub static INTERFACES: phf::Map<&'static str, InterfaceInfo> = ::phf::Map {
    key: 12913932095322966823,
    disps: &[
    ],
    entries: &[
    ],
};
