use std::env;
use std::fs;
use std::io::{BufWriter, Write};
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = Path::new("compute");
    let webidl_dir = Path::new("webidls");

    println!("Output dir: {:?}", out_dir);
    if !out_dir.exists() {
        fs::create_dir(out_dir).unwrap();
    }

    // Collect all .webidl files
    let mut idl_sources: Vec<(String, String)> = Vec::new();
    if webidl_dir.is_dir() {
        for entry in fs::read_dir(webidl_dir).expect("Failed to read webidls/ directory") {
            let entry = entry.expect("Failed to read directory entry");
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) == Some("webidl") {
                println!("cargo::rerun-if-changed={}", path.display());
                let source = fs::read_to_string(&path)
                    .unwrap_or_else(|e| panic!("Failed to read {}: {}", path.display(), e));
                let stem = path.file_stem().unwrap().to_str().unwrap().to_string();
                idl_sources.push((stem, source));
            }
        }
    }

    // Also rerun if the directory contents change
    println!("cargo::rerun-if-changed=webidls/");

    let out_path = out_dir.join("bindings.rs");
    let file = fs::File::create(&out_path).expect("Failed to create bindings.rs");
    let mut w = BufWriter::new(file);

    // Collect all parsed data first, then generate code
    let mut namespaces: Vec<NamespaceData> = Vec::new();
    let mut interfaces: Vec<InterfaceData> = Vec::new();

    for (_stem, source) in &idl_sources {
        let definitions = weedle::parse(source)
            .unwrap_or_else(|e| panic!("Failed to parse WebIDL: {:?}", e));

        for def in &definitions {
            match def {
                weedle::Definition::Namespace(ns) => {
                    let ns_data = extract_namespace(ns);
                    namespaces.push(ns_data);
                }
                weedle::Definition::Interface(iface) => {
                    let iface_data = extract_interface(iface);
                    interfaces.push(iface_data);
                }
                // Skip other definition types for now (typedefs, enums, etc.)
                _ => {}
            }
        }
    }

    // ── Emit the generated Rust code ──

    // Header
    writeln!(w, "// @generated by script_bindings build.rs — DO NOT EDIT").unwrap();
    writeln!(w).unwrap();

    // Emit per-namespace method maps
    for ns in &namespaces {
        emit_method_map(&mut w, &ns.name, &ns.methods);
    }

    // Emit per-interface method + attribute maps
    for iface in &interfaces {
        emit_method_map(&mut w, &iface.name, &iface.methods);
        emit_attribute_map(&mut w, &iface.name, &iface.attributes);
    }

    // Emit top-level namespace lookup map
    emit_namespace_map(&mut w, &namespaces);

    // Emit top-level interface lookup map
    emit_interface_map(&mut w, &interfaces);

    w.flush().unwrap();
}

// ── Data structures ──

struct NamespaceData {
    name: String,
    methods: Vec<MethodData>,
}

struct InterfaceData {
    name: String,
    parent: Option<String>,
    methods: Vec<MethodData>,
    attributes: Vec<AttributeData>,
}

struct MethodData {
    name: String,
    arity: usize,
    is_variadic: bool,
    return_type: String,
}

struct AttributeData {
    name: String,
    readonly: bool,
    type_name: String,
}

// ── Extraction helpers ──

fn extract_namespace(ns: &weedle::NamespaceDefinition) -> NamespaceData {
    let name = ns.identifier.0.to_string();
    let mut methods = Vec::new();

    for member in &ns.members.body {
        if let weedle::namespace::NamespaceMember::Operation(op) = member {
            let method_name = op.identifier
                .as_ref()
                .map(|id| id.0.to_string())
                .unwrap_or_default();

            let arity = op.args.body.list.len();
            let is_variadic = op.args.body.list.iter().any(|arg| {
                matches!(arg, weedle::argument::Argument::Variadic(_))
            });
            let return_type = stringify_return_type(&op.return_type);

            methods.push(MethodData {
                name: method_name,
                arity,
                is_variadic,
                return_type,
            });
        }
    }

    NamespaceData { name, methods }
}

fn extract_interface(iface: &weedle::InterfaceDefinition) -> InterfaceData {
    let name = iface.identifier.0.to_string();
    let parent = iface.inheritance
        .as_ref()
        .map(|inh| inh.identifier.0.to_string());

    let mut methods = Vec::new();
    let mut attributes = Vec::new();

    for member in &iface.members.body {
        match member {
            weedle::interface::InterfaceMember::Operation(op) => {
                let method_name = op.identifier
                    .as_ref()
                    .map(|id| id.0.to_string())
                    .unwrap_or_default();

                let arity = op.args.body.list.len();
                let is_variadic = op.args.body.list.iter().any(|arg| {
                    matches!(arg, weedle::argument::Argument::Variadic(_))
                });
                let return_type = stringify_return_type(&op.return_type);

                methods.push(MethodData {
                    name: method_name,
                    arity,
                    is_variadic,
                    return_type,
                });
            }
            weedle::interface::InterfaceMember::Attribute(attr) => {
                let attr_name = attr.identifier.0.to_string();
                let readonly = attr.readonly.is_some();
                let type_name = stringify_type(&attr.type_.type_);

                attributes.push(AttributeData {
                    name: attr_name,
                    readonly,
                    type_name,
                });
            }
            _ => {}
        }
    }

    InterfaceData { name, parent, methods, attributes }
}

fn stringify_return_type(rt: &weedle::types::ReturnType) -> String {
    match rt {
        weedle::types::ReturnType::Undefined(_) => "undefined".to_string(),
        weedle::types::ReturnType::Type(ty) => stringify_type(ty),
    }
}

fn stringify_type(ty: &weedle::types::Type) -> String {
    match ty {
        weedle::types::Type::Single(single) => {
            match single {
                weedle::types::SingleType::Any(_) => "any".to_string(),
                weedle::types::SingleType::NonAny(non_any) => {
                    stringify_non_any_type(non_any)
                }
            }
        }
        weedle::types::Type::Union(_) => "union".to_string(),
    }
}

fn stringify_non_any_type(ty: &weedle::types::NonAnyType) -> String {
    match ty {
        weedle::types::NonAnyType::Boolean(_) => "boolean".to_string(),
        weedle::types::NonAnyType::ByteString(_) => "ByteString".to_string(),
        weedle::types::NonAnyType::DOMString(_) => "DOMString".to_string(),
        weedle::types::NonAnyType::USVString(_) => "USVString".to_string(),
        weedle::types::NonAnyType::Float32Array(_) => "Float32Array".to_string(),
        weedle::types::NonAnyType::Float64Array(_) => "Float64Array".to_string(),
        weedle::types::NonAnyType::Object(_) => "object".to_string(),
        weedle::types::NonAnyType::Symbol(_) => "symbol".to_string(),
        weedle::types::NonAnyType::Identifier(id) => id.type_.0.to_string(),
        weedle::types::NonAnyType::Sequence(seq) => {
            format!("sequence<{}>", stringify_type(&seq.type_.generics.body.as_ref()))
        }
        weedle::types::NonAnyType::Promise(p) => {
            format!("Promise<{}>", stringify_return_type(&p.generics.body.as_ref()))
        }
        _ => "unknown".to_string(),
    }
}

// ── Code emission helpers ──

fn emit_method_map(w: &mut impl Write, owner_name: &str, methods: &[MethodData]) {
    let map_name = format!("{}_METHODS", owner_name.to_uppercase());

    write!(w, "pub static {}: phf::Map<&'static str, MethodInfo> = ", map_name).unwrap();

    let mut builder = phf_codegen::Map::new();
    for m in methods {
        if m.name.is_empty() {
            continue;
        }
        builder.entry(
            &m.name,
            &format!(
                "MethodInfo {{ name: \"{}\", arity: {}, is_variadic: {}, return_type: \"{}\" }}",
                m.name, m.arity, m.is_variadic, m.return_type
            ),
        );
    }
    writeln!(w, "{};", builder.build()).unwrap();
}

fn emit_attribute_map(w: &mut impl Write, owner_name: &str, attrs: &[AttributeData]) {
    let map_name = format!("{}_ATTRIBUTES", owner_name.to_uppercase());

    write!(w, "pub static {}: phf::Map<&'static str, AttributeInfo> = ", map_name).unwrap();

    let mut builder = phf_codegen::Map::new();
    for a in attrs {
        builder.entry(
            &a.name,
            &format!(
                "AttributeInfo {{ name: \"{}\", readonly: {}, type_name: \"{}\" }}",
                a.name, a.readonly, a.type_name
            ),
        );
    }
    writeln!(w, "{};", builder.build()).unwrap();
}

fn emit_namespace_map(w: &mut impl Write, namespaces: &[NamespaceData]) {
    write!(w, "pub static NAMESPACES: phf::Map<&'static str, NamespaceInfo> = ").unwrap();

    let mut builder = phf_codegen::Map::new();
    for ns in namespaces {
        let methods_ref = format!("{}_METHODS", ns.name.to_uppercase());
        builder.entry(
            &ns.name,
            &format!(
                "NamespaceInfo {{ name: \"{}\", methods: &{} }}",
                ns.name, methods_ref
            ),
        );
    }
    writeln!(w, "{};", builder.build()).unwrap();
}

fn emit_interface_map(w: &mut impl Write, interfaces: &[InterfaceData]) {
    write!(w, "pub static INTERFACES: phf::Map<&'static str, InterfaceInfo> = ").unwrap();

    let mut builder = phf_codegen::Map::new();
    for iface in interfaces {
        let methods_ref = format!("{}_METHODS", iface.name.to_uppercase());
        let attrs_ref = format!("{}_ATTRIBUTES", iface.name.to_uppercase());
        let parent = match &iface.parent {
            Some(p) => format!("Some(\"{}\")", p),
            None => "None".to_string(),
        };
        builder.entry(
            &iface.name,
            &format!(
                "InterfaceInfo {{ name: \"{}\", parent: {}, methods: &{}, attributes: &{} }}",
                iface.name, parent, methods_ref, attrs_ref
            ),
        );
    }
    writeln!(w, "{};", builder.build()).unwrap();
}
